services:
  hw-monitor:
    build: .
    container_name: hwmon
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=0
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///config/cyclone.xml
    volumes:
      - ./cyclone.xml:/config/cyclone.xml:ro
    restart: unless-stopped
